services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    cap_add:
      - NET_ADMIN
  sidecar:
    image: nginx
