# DevContainer公式イメージの利用
# https://github.com/devcontainers/images/tree/main/src/base-debian
FROM mcr.microsoft.com/devcontainers/base:trixie

# 注意: ここでのインストールはroot権限で行われる
# ユーザ権限で更新したいツールは.devcontainer/postCreateCommand.shで行うこと
