services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    environment:
      # プロキシ指定（アプリ/cliが拾う）
      HTTP_PROXY:  http://squid:3128
      HTTPS_PROXY: http://squid:3128
      http_proxy:  http://squid:3128
      https_proxy: http://squid:3128
      # プロキシを経由しない宛先（内部通信）
      NO_PROXY: localhost,127.0.0.1,::1,sidecar,squid,dev,dev-network
    depends_on:
      - squid
    networks:
      - dev-network

  sidecar:
    image: nginx:alpine
    networks:
      - dev-network

  squid:
    # 公式の squid イメージ（Docker Hub の 'squid'）を想定
    image: ubuntu/squid:5.2-22.04_beta
    container_name: squid
    # 自作設定をマウント
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - ./whitelist.txt:/etc/squid/whitelist.txt:ro
      - squid-cache:/var/spool/squid
      - squid-logs:/var/log/squid
    # dev からは dev-network でアクセス、外部へは egress で出る
    networks:
      - dev-network
      - egress

networks:
  # 既存：内部のみ（外へは出ない）
  dev-network:
    driver: bridge
    internal: true
  # 追加：squid 専用の外部向けネットワーク
  egress:
    driver: bridge

volumes:
  squid-cache:
  squid-logs:
