services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
    networks:
      - dev-network
  sidecar:
    image: nginx
    ports:
      - "80:80"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
    internal: true
