services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.cache/devcontainer/go-cache-go-build:/home/vscode/.cache/go-build
      - ~/.cache/devcontainer/go-gomod:/go/pkg/mod
    command: /bin/sh -c "while sleep 1000; do :; done"
